apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-with-gitops-public-api-production
spec:
  destination:
    namespace: default
    server: 'https://aks-roelvandegrint-714c1662.hcp.westeurope.azmk8s.io:443'
  source:
    path: kustomize/public-api/overlays/prod
    repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true