apiVersion: v1
data:
  CosmosDbOptions__ConnectionString: YmtQMnlIcGFSbG0ya0UySTFEMFFMMWkxMGVwWEd0Ukhqc21YajQzeHYzTVdEZTN2aDNROTVNS0hlenY3bUcyblBvTVEwYnE1bUVwbUFDRGJITGNrcFE9PQ==
  MassTransitOptions__AzureServiceBusConnectionString: RW5kcG9pbnQ9c2I6Ly9yb2VsdmFuZGVncmludC5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PWE1R0ZsZ2tRZnEzUEdiY04xR0JGQ0ZBNTNleDIwN2JNQm55VVJEZmZBVmc9
kind: Secret
metadata:
  creationTimestamp: null
  name: public-api-secrets
