apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: public-api-ingress
  namespace: development
spec:
  routes:
  - kind: Rule
    match: Host(`acc.captoso.eu/public`)
    priority: 10
    services:
    - kind: Service
      name: public-api
      port: 80
  