apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-backend
  template:
    metadata:
      name: mongodb-backend
      labels:
        app: mongodb-backend
    spec:
      containers:
      - name: mongodb-backend
        image: mongo:6.0.3
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
