# Default values for public-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: roelvandegrint.azurecr.io/public-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ea544599409fc8c3e4f9669dbb7854256e9581d6"
