apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-api
spec:
  destination:
    namespace: acceptance
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/public-api/overlays/acc
    repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true