apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: public-api-ingress
spec:
  routes:
  - kind: Rule
    match: Host(`dev-mongodb.roelvandegrint.com`)
    priority: 10
    services:
    - kind: Service
      name: public-api
      port: 80
  