apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: public-api-secrets
spec:
  encryptedData:
    CosmosDbOptions__ConnectionString: AgCJktPNBknHKP/OAAKbYoCnGshY8oc/F1SXVT9MjDpxA0Zq4ELSSDqG01pP5GzoS3Tu47Ge/x8+yINjP61QniuDWshBB6zV0/esiQKEU7dANECONUeExOJHw23pjcOQDM1FjKWg1qcUbZsZ6DVe3I3mctcDiY+BczBKDwt2eJDaTYibHiMtX5VBXaaLFb6J4/096gALmIb4yLB0fdcbiTCLo3IpYWRtB2eG8dRAeX87mWg2AAgZynTBwx9O8R22qlWveQ+2Gr8uVbfMbkdAlwQw7c+93CX+e6LAv/KULao/aMIW0nAv+r3ny5Fr/aJNy5Naqriy6rApbnQP9UzfOkz/21xI/qRACncN8YiaYM3KlruVnONfZCOVttU8ebAeTUZjOa/a5i8otxjVB8sQqcutY+0OrQfOgWBv1luESSiIFknzg9sTeoDn8CIpHaMSIQQJUin4fEVmGTZC9zlSV4GVojwwHt6mFOjtRVB/NasTdiRhaszEfgitxCkH+V+iqC7FNDJLg2IbAB8W+sgNhVuPRW/ukekC2gd8X5n8g5bx6fydECmMPVmYopKVq/N0Tcw9GEtr5cCYB0ZE0KgfzduJ5p62b4+DVuVU4XaOkMcbU9yeWGyPm/7KcyzOQJil0ilHflXx4kLSZqXAlhIOA1iYRwqxajfm1Wy4rmHUk+HdjYG/9NnVQOtowIsTkbCy8iTmpBaq+vvd/5kG/27ecKyk1oJQcijOkK9e17md05k13Y9pMTyFw4uKqMczeJSfaPvCopXtQT2ZIaFkrUrlqmsh7q8L61OT8dcaJFTPKQFIYVlWFpWDViQ3
    MassTransitOptions__AzureServiceBusConnectionString: AgCutjskQVk2QcBntiyC4aP9PieXmYlkSaFSXws2TbFOFdNqDSvhWSexTsE5VrgokWgiVYhqs8iqNqASg58XqzJUZhb+4IyTi4jDFOuhg5nwMKXxJ6L4YM76dsRSVxuDYAO8EkEPq1NxgZCYRSmGyo5Ygpe2HDGlz0vgS3otkqVC4icgKuY4FL2kV76n7fImlNGkC6ITaVF/IhPg1Ty7uBDHeWEbHFYB9HmmJMPOQXJFeK3Px0dFowzAOpdJ4E895dVzWYZCvp9KEszH0kFj/e3ovR059/lSee14D0A8ZBmrOMYdpWhE4egg0YoDF6SaZ0x5wKhmSSqrdIy+ERY1fHYm01nNu5coOID5l/TIPT2eLYFA8eExOeTDKltWdN9gru5rAUSm/dLpKg2djraJcLAXeScylIWzuM+0Y/0SPZeBtJC6dmV6rQPLxJBoTqFQq7WrEcfQl7gZXyyYqnzCIKWrDn4oit1848OF1G4O//FntJGKZo2XqG7BzI7HpmmSL7b8gTN4FBWFcMEfoKrcLaZin0h1wdPiyCTpV1KcTJ4yhA2NN7lOeKvLYSb+5LDisDPyvgZpmu/FBesUfVmGieQfnt/VHeauqlJCGXce+V9MJhN3ifI5tA+VnqFLjQq/I+g8Qwz85CNxcts6KzAbd+VcTmdQNA9zqIWQfR3yfm8r75pTEVG6AqnMYoyv/n0A4ePP7l5mjjTh56q23+vzhtRlHO/kG67yNc3tavIE+DiC888Gx4RHNSrnoZcrhQQDqKYKMF+SHZgput8kCJMEvDOHoiLfmp1IvK1HOsAd+kV6UaFqei7G+q1sOeLthltFr5G4x6/DrXNZaQEClQf+eyH0HumZ57JJ0YZEanEXACRyzASD0Gvzo7DYRM5mbV8liKvmzUF6rxRQq+7jzopiS0s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: public-api-secrets

