apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
data:
  logging__LogLevel__Microsoft_AspNetCore: Information
  backendApiBaseAddress: http://backend-api
