apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.namespace }}
data:
  logging__LogLevel__Microsoft_AspNetCore: Information
  backendApiBaseAddress: http://backend-api
