apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: public-api
        image: roelvandegrint.azurecr.io/public-api
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: public-api-configmap
        - secretRef:
            name: public-api-secrets
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
