apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}
        - secretRef:
              name: public-api-secrets
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
