apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-with-gitops-backend-api
spec:
  destination:
    namespace: development
    server: 'https://kubernetes.default.svc'
  source:
    path: backend-api/kustomize/overlays/dev
    repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true