apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservice-with-gitops
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure.git'
      revision: HEAD
      directories:
      - path: argocd/*
      - path: argocd/prod
        exclude: true
  template:
    metadata:
      name: app-of-apps-{{path.basename}}
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        namespace: argocd
        server: 'https://kubernetes.default.svc'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true