apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-api-dev-helm
spec:
  project: default
  source:
    repoURL: 'https://github.com/roelvandegrint/microservices-gitops-infrastructure'
    path: charts/api
    targetRevision: HEAD
    helm:
      valueFiles:
        - public-api.values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: development-helm
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
