apiVersion: v1
kind: ConfigMap
metadata:
  name: public-api-configmap
data:
  BACKENDAPIBASEADDRESS: http://backend-api
  LOGGING__LOGLEVEL__MICROSOFT.ASPNETCORE: Information
  JAEGER__GRPCENDPOINT: http://jaeger-collector:4317
  MONGODBOPTIONS__EMPLOYEESDATABASE: employees
