apiVersion: v1
data:
  DatabaseOptions__ConnectionString: U2VydmVyPXRjcDpyb2VsdmFuZGVncmludC5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz1iYWNrZW5kLWFwaTtQZXJzaXN0IFNlY3VyaXR5IEluZm89RmFsc2U7VXNlciBJRD1yb2VsdmFuZGVncmludDtQYXNzd29yZD0xZ3ZkQzEyMzFWUztNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw==
  MassTransitOptions__AzureServiceBusConnectionString: RW5kcG9pbnQ9c2I6Ly9yb2VsdmFuZGVncmludC5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PWE1R0ZsZ2tRZnEzUEdiY04xR0JGQ0ZBNTNleDIwN2JNQm55VVJEZmZBVmc9
kind: Secret
metadata:
  creationTimestamp: null
  name: backend-api-dev-helm-secrets
