apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: public-api
  template:
    metadata:
      name: public-api
      labels:
        app: public-api
    spec:
      containers:
      - name: public-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: public-api-configmap
        - secretRef:
            name: public-api-secrets
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
